
###Get all books
GET http://localhost:4001/api/books/ HTTP/1.1

###Create a book
POST http://localhost:4001/api/books HTTP/1.1
Content-Type: application/json

{
    "title": "New title",
    "author": "New author",
    "genre": "HORROR",
    "isRead": true
}

###Update a book
PATCH http://localhost:4001/api/books/:id HTTP/1.1
Content-Type: application/json

{
    "title": "Update title",
    "author": "Update author",
    "gerne": "Update genre",
    "isRead": true
}


###Delete a book
DELETE http://localhost:4001/api/books/:id HTTP/1.1